### ISSUE TITLE
Cannot download provider via Terraform registry

### ISSUE THREAD

**Issue by neilfarmer** [DelineaXPM/terraform-provider-tss#33]
**Description of the issue**

Terraform provider cannot be found when following your overview documentation https://registry.terraform.io/providers/DelineaXPM/tss/latest/docs

I am downloading this via the terraform registry.

```
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider delinea/tss: provider
│ registry registry.terraform.io does not have a provider named
│ registry.terraform.io/delinea/tss
│ 
│ All modules should specify their required_providers so that external consumers will
│ get the correct providers when using a module. To see which modules are currently
│ depending on delinea/tss, run the following command:
│     terraform providers
```

I get this on my linux and MacOS machines with the same error.

**Expected behavior**

Terraform should download this provider

**Actual behavior**

Terraform throws an error that it cannot find the provider

**Your environment**

Im running on MacOS Ventura on my Apple M2 Pro laptop.

terraform --version
Terraform v1.3.9
on darwin_arm64

and

Ubuntu Bionic 18.04 x86_64

terraform --version
Terraform v1.3.9
on linux_amd64

**Steps to reproduce**

I created a providers.tf file and added the following code as per your example

```
terraform {
  required_providers {
    tss = {
      source = "delinea/tss"
      version = "1.0.2"
    }
  }
}
```

After running a `terraform init`, I get the following error and cannot find the provider:
```
terraform init

Initializing the backend...

Initializing provider plugins...
- Finding delinea/tss versions matching "1.0.2"...
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider delinea/tss: provider
│ registry registry.terraform.io does not have a provider named
│ registry.terraform.io/delinea/tss
│ 
│ All modules should specify their required_providers so that external consumers will
│ get the correct providers when using a module. To see which modules are currently
│ depending on delinea/tss, run the following command:
│     terraform providers
╵
```

**Comment by gaurava-delinea** [comment]
Please update the providers.tf with the following 
required_providers {
    tss = {
      source = "DelineaXPM/tss"
      version = "2.0.1"
    }
  }
}

**Comment by tylerezimmerman** [comment]
@neilfarmer we have pushed an update, please try again and let us know if you still have issues.

**Comment by neilfarmer** [comment]
@tylerezimmerman that worked! Thank ya!
